get6pm/6pm

.vscode/settings.json
apps/api/v1/index.ts
apps/api/v1/middlewares/auth.ts
apps/api/v1/routes/auth.ts
apps/api/v1/routes/users.ts
apps/api/v1/services/user.service.ts
apps/api/v1/validation/index.ts
apps/api/v1/validation/user.zod.ts

feat(api): add `POST /users`

---

apps/api/v1/index.ts
apps/api/v1/routes/budgets.ts
apps/api/v1/services/budget-invitation.service.ts
apps/api/v1/services/budget.service.ts
apps/api/v1/validation/budget.zod.ts
apps/api/v1/validation/index.ts

- `GET /budgets?permission`
- `POST /budgets`
- `GET /budgets/:budgetId`
- `PUT /budgets/:budgetId`
- `DELETE /budgets/:budgetId`

feat(api): add budget API routes

---

apps/api/v1/validation/user.zod.ts
apps/mobile/app/(app)/(tabs)/explore.tsx
apps/mobile/app/(app)/_layout.tsx
apps/mobile/app/_layout.tsx
apps/mobile/components/auth/auth-email.tsx
apps/mobile/components/auth/auth-social.tsx
apps/mobile/mutations/user.ts
apps/mobile/queries/auth.ts

Resolves https://github.com/sixpm-ai/6pm/issues/5

feat(mobile): create db user after sign up

---

.vscode/settings.json
apps/api/v1/index.ts
apps/api/v1/routes/budgets.ts
apps/api/v1/routes/categories.ts
apps/api/v1/services/category.service.ts
packages/validation/src/category.zod.ts
packages/validation/src/index.ts

feat(api): add category APIs

---

apps/api/package.json

Updated the build script in `package.json` to include `prisma generate` before running `next build`. Kudos to https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/vercel-caching-issue
Modified the build script in the `package.json` file from `next build` to `prisma generate && next build`.
Run the build script using `npm run build` and ensure that Prisma client is generated before the Next.js build process is initiated.
This change ensures that the Prisma client is always up-to-date before building the Next.js application, preventing potential runtime issues related to the database schema.
---

fix(api): fix vercel cache for prisma generated

---

apps/mobile/app/(app)/_layout.tsx
apps/mobile/app/(app)/new-record.tsx
apps/mobile/components/numeric-pad/index.ts
apps/mobile/components/numeric-pad/numeric-pad.tsx
apps/mobile/components/text-ticker/index.ts
apps/mobile/components/text-ticker/text-ticker.tsx

https://github.com/sixpm-ai/6pm/assets/16166195/da1d82b7-ef35-49ae-90e0-640a29dcd656

feat(mobile): [Transaction] add basic transaction amount input

---

apps/mobile/app/(app)/new-record.tsx
apps/mobile/components/transaction/select-account-field.tsx
apps/mobile/components/transaction/transaction-form.tsx
apps/mobile/queries/wallet.ts

https://github.com/sixpm-ai/6pm/assets/16166195/363d8616-28d6-40e6-9b60-564af3224f7d

feat(mobile): [Transaction] add select wallet account field

---

apps/mobile/app/(app)/new-record.tsx
apps/mobile/app/_layout.tsx
apps/mobile/components/common/toast.tsx
apps/mobile/mutations/transaction.ts
apps/mobile/package.json
pnpm-lock.yaml

Resolves https://github.com/sixpm-ai/6pm/issues/39
https://github.com/sixpm-ai/6pm/assets/16166195/b19780bc-ab86-4f48-b811-1f94235d4cc2

feat(mobile): [Transaction] add create transaction with success toast

---

apps/api/v1/routes/transactions.ts
apps/api/v1/services/category.service.ts
apps/api/v1/services/wallet.service.ts

Fixes bug transaction always be negative

feat(api): add check transaction category for amount

---

apps/mobile/components/transaction/transaction-item.tsx
apps/mobile/tailwind.config.js

feat(mobile): add negative color for transaction item

---

apps/mobile/components/budget/burndown-chart.tsx
apps/mobile/lib/theme.ts
apps/mobile/package.json
apps/mobile/stores/budget/hooks.tsx
packages/currency/src/formatter.ts
packages/currency/src/index.ts
pnpm-lock.yaml

feat(mobile): [Budget] add burndown chart

---

apps/mobile/index.js

https://x.com/sregg/status/1819467674755518916
https://github.com/formatjs/formatjs/issues/4463

fix(mobile): force load intl polyfills

---

apps/mobile/app.json
apps/mobile/app/_layout.tsx
apps/mobile/index.js
apps/mobile/package.json

Note:
Set `EXPO_USE_METRO_WORKSPACE_ROOT=0` on EAS for production build, this variable is only necessary on development.
https://github.com/expo/eas-cli/issues/2280#issuecomment-2183524390

fix(mobile): refactor expo setup to adapt expo-updates

---

apps/mobile/components/transaction/select-account-field.tsx
apps/mobile/components/transaction/select-category-field.tsx

https://github.com/user-attachments/assets/f10ccbce-07b0-4fac-8d53-63c6e4ac443d

feat(mobile): quick add new category from transaction form

---

apps/api/v1/services/budget.service.ts
apps/mobile/app/(app)/wallet/[walletId].tsx
apps/mobile/app/(app)/wallet/new-account.tsx
apps/mobile/components/budget/budget-form.tsx
apps/mobile/components/ui/collapsible.tsx
apps/mobile/components/wallet/account-form.tsx
apps/mobile/components/wallet/select-balance-state-field.tsx
apps/mobile/package.json
apps/mobile/queries/wallet.ts
packages/validation/src/budget.zod.ts
packages/validation/src/wallet.zod.ts
pnpm-lock.yaml

feat(mobile): allow input negative wallet balance and float numbers

---

apps/mobile/app/(app)/(tabs)/index.tsx
apps/mobile/components/budget/budget-statistic.tsx
apps/mobile/components/home/category-chart.tsx
apps/mobile/components/home/wallet-statistics.tsx
apps/mobile/locales/en/messages.po
apps/mobile/locales/vi/messages.po
apps/mobile/stores/transaction/hooks.tsx

Resolves https://github.com/get6pm/6pm/issues/36
https://github.com/user-attachments/assets/981d4b5c-6866-49f3-9512-ac650057220a

feat(mobile): add category chart and filter by category

---

apps/api/prisma/migrations/20240901110039_remove_budget_period_uniqe_constraint/migration.sql
apps/api/prisma/schema.prisma
packages/validation/src/prisma/index.ts

This constraint causes new period configs not be able to created.

fix(api): remove unique constraint on budgetId with period config

---

apps/mobile/app/(app)/_layout.tsx
apps/mobile/components/auth/auth-local.tsx

Resolves https://github.com/get6pm/6pm/issues/251

fix(mobile): fix local auth guard cause router crashes

---

apps/mobile/app/(app)/budget/[budgetId]/index.tsx
apps/mobile/stores/budget/hooks.tsx
packages/validation/src/budget.zod.ts

Resolves https://github.com/get6pm/6pm/issues/322

fix(mobile): prevent set budget amount zero

---

apps/mobile/components/common/tab-bar.tsx

Resolves https://github.com/get6pm/6pm/issues/323

fix(mobile): fix initial tabbar active position

---

apps/api/v1/services/transaction.service.ts
packages/validation/src/transaction.zod.ts

Related: https://github.com/get6pm/6pm/issues/339

feat(api): includes wallet and budget to transaction queries

---

apps/api/.env.development

Ensure API timezone matches the production serverless services for better development and debugging.

chore(api): add default .env.development

---

apps/api/v1/index.ts

fix(api): add missing revenuecat webhook route
