get6pm/6pm

apps/api/prisma/generated/zod/index.ts
apps/api/prisma/migrations/20240606080412_add_full_schemas/migration.sql
apps/api/prisma/schema.prisma

Closes #3
⚠️ TODO: Migrate before merging

feat(api): add prisma schema

---

apps/api/v1/index.ts
apps/api/v1/routes/wallets.ts

feat(api): add wallet API routes

---

apps/api/prisma/migrations/20240620165734_cascading_transaction_on_wallet_or_user_deleted/migration.sql
apps/api/prisma/schema.prisma
apps/mobile/app/(app)/_layout.tsx
apps/mobile/app/(app)/wallet/[walletId].tsx
apps/mobile/app/(app)/wallet/accounts.tsx
apps/mobile/components/ui/skeleton.tsx
apps/mobile/components/wallet/account-form.tsx
apps/mobile/components/wallet/wallet-account-item.tsx
apps/mobile/mutations/wallet.ts

- adjust balance correctly on update
- cascade transactions on delete wallet
Resolves https://github.com/sixpm-ai/6pm/issues/28

feat(mobile): [Wallet] update and delete wallet account

---

apps/mobile/components/auth/auth-email.tsx

Resolves https://github.com/sixpm-ai/6pm/issues/84

fix(mobile): fix email verification code requested twice

---

apps/mobile/app/(app)/new-record.tsx
apps/mobile/components/form-fields/input-field.tsx
apps/mobile/components/numeric-pad/numeric-pad.tsx
apps/mobile/components/transaction/transaction-form.tsx
packages/validation/src/transaction.zod.ts

https://github.com/sixpm-ai/6pm/assets/16166195/7a3dff6d-5d1f-4ab1-9ce5-4f1870e3c432

feat(mobile): [Transaction] add transaction form layout

---

apps/mobile/components/transaction/select-category-field.tsx
apps/mobile/components/transaction/transaction-form.tsx

feat(mobile): [Transaction] add select category field

---

apps/api/v1/routes/transactions.ts
apps/api/v1/services/transaction.service.ts

Also populate category field on transaction record.

feat(api): [Transaction] Paginate transactions by date instead of createdAt

---

apps/api/v1/routes/transactions.ts
apps/api/v1/services/transaction.service.ts
apps/mobile/mutations/transaction.ts

Please help purging all historical transactions in db @duongdev

fix(mobile): [Transaction] new transaction amount should be negative

---

.vscode/settings.json
apps/api/lib/log.ts
apps/api/package.json
apps/api/v1/routes/transactions.ts
apps/api/v1/services/ai.service.ts
pnpm-lock.yaml

feat(api): add openai transaction data

---

apps/mobile/components/category/select-category-icon-field.tsx
apps/mobile/components/transaction/select-account-field.tsx
apps/mobile/components/transaction/select-category-field.tsx
apps/mobile/components/transaction/select-date-field.tsx
apps/mobile/components/transaction/transaction-form.tsx
apps/mobile/components/wallet/select-account-icon-field.tsx
apps/mobile/components/wallet/select-currency-field.tsx
apps/mobile/global.css
apps/mobile/lib/theme.ts

feat(mobile): improve dark mode

---

apps/mobile/app/(app)/transaction/new-record.tsx
apps/mobile/app/(app)/wallet/[walletId].tsx

perf(mobile): optimize invalidateQueries on adjust balance & new record

---

packages/currency/src/currencies.json

chore(currency): move VND on top

---

apps/mobile/app/(app)/_layout.tsx
apps/mobile/app/(app)/transaction/[transactionId].tsx
apps/mobile/components/transaction/transaction-form.tsx
apps/mobile/mutations/transaction.ts
apps/mobile/queries/transaction.ts

Resolves https://github.com/get6pm/6pm/issues/112

feat(mobile): [Transaction] add update and delete transaction

---

apps/api/v1/routes/transactions.ts
apps/api/v1/services/ai.service.ts
apps/mobile/mutations/transaction.ts

Includes user's categories and language (Eng only for now).

feat(api): improve gpt prompt

---

apps/mobile/app/(app)/(tabs)/budgets.tsx
apps/mobile/components/budget/budget-item.tsx
apps/mobile/components/budget/budget-statistic.tsx
apps/mobile/components/common/circular-progress.tsx

https://github.com/user-attachments/assets/c7e88635-40ee-4236-b2b2-eabdebb753f7

feat(mobile): [Budget] animate budget list

---

apps/mobile/components/budget/budget-form.tsx
apps/mobile/components/budget/select-budget-type-field.tsx
apps/mobile/components/budget/select-period-type-field.tsx

feat(mobile): temporary disable budget type and period in create form

---

apps/mobile/app/(app)/(tabs)/settings.tsx
apps/mobile/components/setting/profile-card.tsx
apps/mobile/package.json
pnpm-lock.yaml

i'm sorry
https://github.com/user-attachments/assets/30ab57c8-f054-4c23-b095-f75c9efce32d

feat(mobile): add interactive profile card

---

apps/mobile/app/(app)/(tabs)/index.tsx
apps/mobile/components/budget/select-budget-type-field.tsx
apps/mobile/components/budget/select-period-type-field.tsx
apps/mobile/components/home/header.tsx
apps/mobile/components/home/select-wallet-account.tsx
apps/mobile/components/ui/select.tsx
packages/validation/src/transaction.zod.ts

Resolves https://github.com/get6pm/6pm/issues/37
https://github.com/user-attachments/assets/3ed3d189-cc03-4121-92d5-98e200ee252f

feat(mobile): [Transaction] filter by account

---

apps/mobile/app/(app)/transaction/[transactionId].tsx
apps/mobile/app/(app)/transaction/new-record.tsx
apps/mobile/components/transaction/select-budget-field.tsx
apps/mobile/components/transaction/transaction-form.tsx
apps/mobile/components/ui/select.tsx
apps/mobile/mutations/transaction.ts
packages/validation/src/transaction.zod.ts

Resolves https://github.com/get6pm/6pm/issues/118

feat(mobile): [Transaction] create transaction with budget

---

apps/mobile/eas.json

https://docs.expo.dev/build/building-from-github/#set-the-image-field-in-your-easjson

feat(mobile): add image to eas.json

---

apps/mobile/app/(app)/_layout.tsx
apps/mobile/app/(app)/profile.tsx
apps/mobile/components/common/user-avatar.tsx
apps/mobile/components/setting/profile-card.tsx
apps/mobile/components/ui/button.tsx

Resolves https://github.com/get6pm/6pm/issues/165

feat(mobile): [Profile] update user profile and delete account

---

apps/mobile/app/(app)/(tabs)/index.tsx

There's an issue when user changes default currency. Will fix later.
| Light | Dark |
| ----- | ---- |
|  ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/enG7ZCYKqKDoyEbo2IZD/64fe9c43-ed9a-45fb-999a-028cd7c159de.png)     | ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/enG7ZCYKqKDoyEbo2IZD/9c22185b-56da-4c9e-b0c4-5d65727759a4.png)     |

feat(mobile): [TransactionList] add sum by day

---

apps/mobile/components/home/wallet-statistics.tsx

feat(mobile): use transactions in store to calculate wallet stats

---

apps/mobile/app/(app)/(tabs)/_layout.tsx
apps/mobile/app/(app)/_layout.tsx
apps/mobile/app/(aux)/_layout.tsx
apps/mobile/app/_layout.tsx
apps/mobile/components/budget/budget-statistic.tsx
apps/mobile/components/common/amount-format.tsx
apps/mobile/components/common/toast.tsx
apps/mobile/components/numeric-pad/numeric-pad.tsx
apps/mobile/components/text-ticker/text-ticker.tsx
apps/mobile/components/transaction/transaction-form.tsx

also adjust incorrect font weight

fix(mobile): fix header font to Inter

---

apps/mobile/components/transaction/select-category-field.tsx
apps/mobile/package.json
pnpm-lock.yaml

https://github.com/user-attachments/assets/df8fdcd5-c413-45e5-9b7b-34f0f83c6680

feat(mobile): genius way to display full category name

---

apps/mobile/app/(app)/transaction/[transactionId].tsx
apps/mobile/app/(app)/transaction/new-record.tsx
apps/mobile/components/auth/auth-email.tsx
apps/mobile/components/common/toolbar.tsx
apps/mobile/components/form-fields/input-field.tsx
apps/mobile/components/transaction/scanner.tsx

related to some incomplete implementation of nativewind animations

fix(mobile): fix transform with key of translateY crashes

---

apps/mobile/app/(app)/(tabs)/budgets.tsx
apps/mobile/app/(app)/budget/[budgetId]/index.tsx
apps/mobile/components/budget/budget-item.tsx
apps/mobile/components/budget/budget-statistic.tsx
apps/mobile/components/budget/burndown-chart.tsx
apps/mobile/components/common/circular-progress.tsx
apps/mobile/stores/budget/hooks.tsx

The code is 🤢 and probably not all correct but let's pray.

feat(mobile): correct budget statistic amount

---

apps/api/v1/routes/transactions.ts
apps/api/v1/services/budget.service.ts
apps/api/v1/services/transaction.service.ts
packages/utilities/src/date/period.ts

Resolves https://github.com/get6pm/6pm/issues/236

feat(api): verify and create period config base on transaction date

---

apps/mobile/app/(app)/(tabs)/index.tsx
apps/mobile/app/(app)/budget/[budgetId]/index.tsx
apps/mobile/components/budget/budget-item.tsx
apps/mobile/components/common/amount-format.tsx
apps/mobile/components/home/wallet-statistics.tsx
apps/mobile/components/transaction/select-budget-field.tsx
apps/mobile/components/transaction/transaction-form.tsx
apps/mobile/components/wallet/wallet-account-item.tsx
apps/mobile/stores/budget/hooks.tsx
apps/mobile/stores/exchange-rates/hooks.tsx
apps/mobile/stores/exchange-rates/queries.ts
apps/mobile/stores/exchange-rates/store.ts
packages/currency/src/index.ts

Resolves https://github.com/get6pm/6pm/issues/209

feat(mobile): exchange rates

---

apps/mobile/app/(app)/paywall.tsx
apps/mobile/hooks/use-purchases.ts

Resolves https://github.com/get6pm/6pm/issues/268

fix(mobile): refetch user entitlements after purchases

---

apps/api/v1/constants/wallet.const.ts
apps/mobile/app/(app)/(tabs)/_layout.tsx
apps/mobile/app/(app)/(tabs)/budgets.tsx
apps/mobile/app/(app)/_layout.tsx
apps/mobile/app/(app)/category/[categoryId].tsx
apps/mobile/app/(app)/category/index.tsx
apps/mobile/app/(app)/transaction/new-record.tsx
apps/mobile/app/(app)/wallet/accounts.tsx
apps/mobile/components/transaction/scanner.tsx
apps/mobile/components/transaction/select-budget-field.tsx
apps/mobile/components/transaction/transaction-form.tsx
apps/mobile/hooks/use-purchases.ts
apps/mobile/lib/constaints.ts

Resolves https://github.com/get6pm/6pm/issues/268

feat(mobile): guard features base on user entitlement

---

apps/api/v1/routes/transactions.ts
apps/mobile/stores/transaction/hooks.tsx
packages/utilities/src/index.ts
packages/utilities/src/transactions.ts

Add `getTransactionAmountBasedOnCategory` in `@6pm/utilities` to get the transaction amount based on the category.

feat(utils): add getTransactionAmountBasedOnCategory util

---

apps/api/package.json
apps/api/v1/routes/users.ts
apps/api/v1/services/clerk.service.ts
apps/api/v1/services/user.service.ts
pnpm-lock.yaml

Now POST /users will actually upsert the user in database. When creating user in database fails, delete the existing user on Clerk.

feat(api): improve create user

---

apps/mobile/app/(app)/transaction/new-record.tsx

No more "Uncategorized" transactions

feat(mobile): create transaction with Other Expense as default category

---

apps/mobile/app/(app)/budget/[budgetId]/edit.tsx

fix(mobile): unset default budget

---

apps/mobile/tailwind.config.js

feat(mobile): slightly increase font size

---

apps/mobile/locales/provider.tsx
packages/utilities/src/date/dayjs.ts

Issue: https://github.com/get6pm/6pm/issues/283

feat(mobile): add Vietnamese support for dates
